name: clean_architecture_tdd_course

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.1.0'
          channel: 'stable'
          architecture: x64
      - run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/stable-2.1.0-x64
          flutter build bundle

      - name: Install Dependencies
        run: flutter packages get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
