name: clean_architecture_tdd_course

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter packages get

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
  
      - name: Run octocov              
        uses: k1LoW/octocov-action@v0.51.6

      - name: Test Reporter
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test report           # Name of the check run which will be created
          path: test-results.json    # Path to test results
          reporter: 'flutter-json'   
            
